### ISSUE TITLE
Mono tracks not properly assigned with Bounce-To-Disk feature

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#72]
A known issue, but for documentation purposes I will post it here.

When a mono sound is assigned an output on the MIXER program's INDIV function, it will still bounce to a stereo track with VMPC's Bounce-To-Disk function.

Steps to reproduce:

1. A stereo sample is assigned to output 1/2

2. Mono samples (usually drum and bass sounds) are assigned to single mono outputs 3, 4, 5, 6, 7, and 8 respectively

3. Shift+Play From Start will bring up the Bounce-to-Disk dialog; bounce the track on or offline

4. Bouncing the sequence to disk results in all stereo tracks being produced, even if mono channels were assigned on INDIV in the MIXER

Result: the stereo sample on output 1/2 is correctly bounced as it is indeed a stereo track. Mono outputs 3 & 4, 5 & 6, and 7 & 8, are summed together in a stereo track, with one instrument fully panned to the left, and the other fully panned to the right, rather than being individual tracks with a mono (centered) sound.

Izzy may refer to a fully constructed beat I sent him 'bounce.7z' to reproduce the results himself.

**Comment by izzyreal** [comment]
I've implemented the split L/R functionality in https://github.com/izzyreal/mpc/commit/aa153d6d8d4f408ccbdb1b9be04bd565e0eefd1c.

For now I have removed the `Rate:` setting, because it wasn't actually working either. Bounces will always be recorded in the same sample rate as you have configured in the Audio/MIDI Settings.

Please try the L/R and let me know how that works.

**Comment by izzyreal** [comment]
The idea with the current direct-to-disk recording, is that all the outputs are bounced. The Split L/R option allows you to automatically split the result into left and right channels. With that new commit you'll get files named L.wav, R.wav, 1.wav - 8.wav.

Maybe it would also be cool to have a direct-to-disk option that writes a WAV for each non-silent MPC mixer channel, which correlates to a virtual pad (i.e. pads A01 - D16). That seems more congruent with what you're expecting.

**Comment by brownounces** [comment]
> The idea with the current direct-to-disk recording, is that all the outputs are bounced.

Perhaps my understanding of the feature is wrong -- are the bounced tracks supposed to correlate at all with the INDIV function on the mixer, or is it bouncing based on the sequencer tracks? 

My thinking was that the bounce would use the INDIV settings during the recording, and bounce the recording to individual .wavs based on those assignments. That would essentially recreate the "8 Outputs" functionality that the hardware 2000XL had without needing to make a sophisticated pad bouncer. 

If that is not how bounce-to-disk is intended to work, you should consider it doing it this way -- the original 8 Outputs functionality tracked out from the INDIV channels rather than the sequencer tracks. That would give the user more control over the separation of each sound in the .wav output and be truer to the 2000XL functionality.

**Comment by izzyreal** [comment]
> My thinking was that the bounce would use the INDIV settings during the recording, and bounce the recording to individual .wavs based on those assignments. That would essentially recreate the "8 Outputs" functionality that the hardware 2000XL had without needing to make a sophisticated pad bouncer.

Not sure what you mean by "Use the INDIV settings" 🤔 

The feature as it is currently implemented, simply records all outputs. So L, R, and 1...8, regardless of any settings in the (V)MPC. So whatever your project happens to send to those outputs, that is what is recorded. The bounce process itself does not care about specific INDIV-related settings (or sequencer tracks for that matter). It just peeks what passes through each output, and saves it to disk. This may be 100% silence if you're not directing any sounds to an output.

It's also possible that sounds are bounced to for example both L/R and 1/2. This happens when you don't dial the STEREO fader down in the MIXER screen, and you have dialed the INDIV fader up and selected 1/2 for a given pad (note that channels in the MIXER screen correlate to pads). This is the same behaviour as the original. Just making sure we're on the same page regarding original behaviour.

**Comment by brownounces** [comment]
As it would happen, there is no bug or missing feature here -- I'm just a major league moron. Outputs are assigned with on Channel Settings under the 'Out:' designation. For some reason, I thought INDIV assigned the outputs and that bounce-to-disk just didn't read it. Have mercy.

**Comment by izzyreal** [comment]
No need to go to Channel Settings. You can assign individual outputs by moving up in the INDIV mixer and using the DATA wheel.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/3707432/235326368-c27d7805-bbe7-40fc-bb83-5ed0cc8346eb.png">

**Comment by brownounces** [comment]
Wait, that's what I have been trying to say all along hahah. In my experience, assigning pads to INDIV mixer outputs doesn't separately track them for bouncing. All of the bounced files result in a stereo track, even if they are mono. This itself wouldn't be a big deal, but single-output tracks (mono sounds) are summed into one stereo track, with one sound panned to the left and one sound panned to the right.

Example: All of BANK A is assigned to output 1/2 (stereo) on the mixer. On BANK B, Pad 1 is assigned to output 3 (mono) and Pad 2 is assigned to output 4 (mono). What will happen is output 3 and 4 will be merged on bounce-to-disk, with output 3 being panned to the left and output 4 being panned to the right in one stereo track, rather than as separate mono tracks.

**Comment by izzyreal** [comment]
> All of the bounced files result in a stereo track, even if they are mono. 


Not anymore, you now have a choice. See https://github.com/izzyreal/vmpc-juce/issues/72#issuecomment-1528804222.
